/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedBackground: typeof import('./src/components/background/AnimatedBackground.vue')['default']
    EditModal: typeof import('./src/components/sys/dept/EditModal.vue')['default']
    FilePreviewModal: typeof import('./src/components/common/FilePreviewModal.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    PrivacyPolicy: typeof import('./src/components/sys/auth/PrivacyPolicy.vue')['default']
    ResetSelfPassword: typeof import('./src/components/sys/auth/ResetSelfPassword.vue')['default']
    RichContentViewer: typeof import('./src/components/common/RichContentViewer.vue')['default']
    RichEditor: typeof import('./src/components/wiki/RichEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectAssignModal: typeof import('./src/components/sys/permission/SelectAssignModal.vue')['default']
    SelectModal: typeof import('./src/components/sys/dept/SelectModal.vue')['default']
    SideBar: typeof import('./src/components/sys/sideBar/SideBar.vue')['default']
    SidebarItem: typeof import('./src/components/sys/sideBar/SidebarItem.vue')['default']
    SingleSelectModal: typeof import('./src/components/sys/people/SingleSelectModal.vue')['default']
    UserAgreement: typeof import('./src/components/sys/auth/UserAgreement.vue')['default']
    ValidateCaptchaModal: typeof import('./src/components/sys/captcha/ValidateCaptchaModal.vue')['default']
  }
}
